### PR TITLE
Pctssi

### PR DESCRIPTION
**Pull request by BiSeye**
2019 World Values & ACS update

### CODE REVIEW

**Comment by Vanie2020** [comment]
> @BiSeye this seems to have the world value for PCTSSI but the metric files for Per capita income?

Not sure why.  I sent SSI and PCI in separate commits in their own branches 
How can I fix it or do i need to do a thing over again?

**Comment by timstallmann** [comment]
@BiSeye can you point me to where the SSI commits are? I can try to pull them into this branch and then merge..

**Comment by Vanie2020** [comment]
It showing as updated in THIS branch. may just trying making a new branch for PCTSSI and making sure world values and metrics are in there as fresh.  Ill do that next might be the easiest way to correct this one

**Comment by JohnKilleen** [comment]
@timstallmann 's suggestion of pulling in the SSI commits feels appropriate here. The PCTSSI branch has only the config.js world value update for PCTSSI, not the data table updates. (https://github.com/DataWorks-NC/durham-quality-of-life-data/blob/PCTSSI/config/data.js) @BiSeye Can you push the table updates to that branch too?

**Comment by Vanie2020** [comment]
It should all be there now

**Comment by timstallmann** [comment]
looks good, thx!

**Pull request merged**
